#WAP to Print Current Date....
from datetime import date
today=date.today()
#printing current date in DD/MM/YY format...
d1=today.strftime("%d/%m/%Y")
print("d1=",d1)
#printing current date in textual 'month, day and year' format...
d2=today.strftime("%B/%d/%Y")
print("d2=",d2)
#printing current date in MM/DD/YY format...
d3=today.strftime("%m/%d/%y")
print("d3=",d3)
#printing current date in Month abbreviation day and year format...
d4=today.strftime("%b-%d-%y")
print("d4=",d4)